#!/usr/bin/env python3
"""Build the six static content hubs from one consistent presentation template."""

from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "FlitKey HP"

PAGES = {
    "linux-text-expansion": {
        "tag": "LINUX TEXT EXPANSION",
        "title": "Linux text expansion across X11 and Wayland",
        "description": "Practical Linux text expansion guidance for X11, Wayland, GNOME, KDE Plasma, Hyprland, Ubuntu, Debian, Mint, and Pop!_OS.",
        "answer": "Start by checking the session, not the distribution name. FlitKey supports typed keyword expansion and global hotkeys in an X11 session when its X11 utilities are available. In a native Wayland session, FlitKey 0.5.0 uses Quick Insert and clipboard paste. If automatic Wayland triggers are essential, evaluate another tool's documented approach and permission model.",
        "sections": [
            ("session", "The session determines the workflow", "<p>Run <code>echo $XDG_SESSION_TYPE</code> before choosing or troubleshooting a Linux text expander. An <code>x11</code> result means FlitKey can use its X11 backend. A <code>wayland</code> result means it selects the Wayland fallback backend at startup. The desktop can still run individual XWayland applications, but FlitKey does not switch input backends for each focused window.</p><p>This distinction prevents a common diagnosis error. Ubuntu, Fedora, Debian, Mint, and Pop!_OS are distributions; GNOME, KDE Plasma, and Hyprland are desktop or compositor environments; X11 and Wayland are session protocols. Two machines with the same distribution can therefore expose different text-expansion capabilities.</p>"),
            ("x11", "What FlitKey does on X11", "<p>On X11, FlitKey listens for keyword triggers through <code>xinput</code> and inserts text with <code>xdotool</code>. Global hotkeys and the <code>Alt+Space</code> picker shortcut are available when the required utilities and desktop permissions are present. Test a plain-text editor first, then the browser, terminal, IDE, office suite, and chat applications that matter to you.</p><p>X11 access is broad by design. A text expander that observes global keys should be treated as sensitive desktop software. Install from a source you trust, review the public code when appropriate, and avoid storing passwords or private keys in snippet files.</p>"),
            ("wayland", "What remains available on Wayland", "<p>FlitKey's Wayland-aware workflow keeps the visual snippet manager, local storage, placeholder rendering, tray controls, and autostart. Open Quick Insert from the main application or tray menu, search for a snippet, select it, return to the target window, and paste. Version 0.5.0 does not register a global picker shortcut, typed triggers, or global expansion hotkeys on Wayland.</p><p>That behavior is intentionally narrower than a claim of “native Wayland expansion.” Other projects may use experimental device access, input methods, accessibility services, or compositor-specific protocols. Compare the permission tradeoff and supported environments rather than assuming every Wayland implementation behaves identically.</p>"),
            ("choose", "Choose by required capability", "<p>Choose FlitKey when a visual library, local JSON storage, simple placeholders, and a clipboard-based Wayland workflow solve the actual job. Choose Espanso when file-based configuration, packages, regex triggers, forms, or scripts matter more. AutoKey remains useful for X11 users who want Python-powered desktop automation rather than a focused snippet manager.</p><p>If you move between Linux and Windows, test the same small fixture on both platforms: a single line, multiline reply, Unicode text, date placeholder, clipboard placeholder, and cursor marker. Record failures by operating system, session, application, and version instead of declaring blanket compatibility.</p>"),
            ("install", "A safe Linux evaluation", "<ol><li>Back up any existing snippet library.</li><li>Install the Debian package on a supported Debian-based system, or run the reviewed source on another distribution.</li><li>Confirm the backend and capability report inside FlitKey.</li><li>Create non-sensitive test snippets and try the applications you use daily.</li><li>Enable autostart only after the manual test passes.</li></ol><p>FlitKey does not currently claim a published Flatpak, Snap, or AUR package. Use the documentation and GitHub release page as the source of truth for available installation methods.</p>"),
        ],
        "cards": [("/wayland-text-expander", "Wayland workflow guide"), ("/espanso-vs-flitkey/", "FlitKey vs Espanso"), ("/espanso-migration-guide", "Import Espanso YAML")],
    },
    "windows-text-expansion": {
        "tag": "WINDOWS TEXT EXPANSION",
        "title": "Windows text expansion without unnecessary scripting",
        "description": "Windows 11 text expansion guidance covering AutoHotkey, TextExpander, aText, local storage, imports, SmartScreen, and visual snippet workflows.",
        "answer": "FlitKey is a focused option for Windows users who want visual plain-text snippets, local storage, no account, and no subscription. AutoHotkey is stronger for general automation. TextExpander is stronger for sync and teams. aText may suit Windows and macOS users who prefer its commercial feature set. Test the applications and data controls you actually require.",
        "sections": [
            ("fit", "Begin with the job, not a feature count", "<p>A support agent inserting approved replies has a different requirement from a developer remapping keys or an operations team distributing shared content. FlitKey concentrates on reusable text, keyword triggers, hotkeys, a searchable picker, a few dynamic placeholders, and local JSON storage. It does not attempt to replace a Windows automation language or a managed team-content platform.</p><p>Write down five required workflows before comparing tools. Include the destination applications, formatting needs, dynamic fields, collaboration model, and whether the data may leave the endpoint. A smaller product that covers all five jobs can be a better fit than a larger product whose differentiating features remain unused.</p>"),
            ("tools", "Where the main alternatives fit", "<p>AutoHotkey is the natural choice when text expansion is one part of a larger Windows automation system involving window management, key remapping, conditional logic, or application control. FlitKey is easier to inspect visually for straightforward snippets but deliberately lacks that automation depth.</p><p>TextExpander is a subscription product built around synchronized content and organizational workflows. Those capabilities can justify the account and recurring cost for teams. aText provides a commercial visual expander for Windows and macOS. FlitKey is differentiated by its free MIT license, Linux support, and absence of a hosted account—not by being universally more capable.</p>"),
            ("installer", "Handle the unsigned installer honestly", "<p>FlitKey 0.5.0's Windows installer is not code-signed. Microsoft Defender SmartScreen may display “Unknown Publisher.” Download from the project's GitHub release, confirm that the filename and version match the documentation, and follow your organization's software-approval process. Do not dismiss security warnings on managed or high-risk machines without authorization.</p><p>The application uses Windows keyboard hooks and input APIs for supported triggers and hotkeys. This is expected for a system-wide text expander, but it also means the process has sensitive input access. Source availability helps inspection; it does not replace binary provenance, endpoint security, or a controlled update process.</p>"),
            ("apps", "Test application behavior", "<p>Start in Notepad or another disposable plain-text editor. Then test Outlook, browsers, Visual Studio Code, PowerShell, terminals, remote-desktop sessions, and line-of-business applications separately. Synthetic input, elevated windows, rich-text editors, and security software can change the result.</p><p>Use a repeatable fixture containing punctuation, Unicode, multiple lines, <code>{{date}}</code>, <code>{{clipboard}}</code>, and <code>{{cursor}}</code>. Record the Windows build, application version, FlitKey version, and outcome. That evidence is more useful than an undated claim that a tool works “everywhere.”</p>"),
            ("migration", "Migrate in reversible batches", "<p>FlitKey imports supported AutoHotkey, Espanso, CSV, TSV, and JSON records. Importing a file is not the same as reproducing its source application's execution engine. Scripts, rich content, conditional automation, forms, and proprietary database features may require redesign or may have no FlitKey equivalent.</p><ol><li>Back up the source library and FlitKey configuration.</li><li>Import a copied sample.</li><li>Review every generated trigger and expansion.</li><li>Test real destination applications.</li><li>Keep the old tool available until verification is complete.</li></ol>"),
        ],
        "cards": [("/autohotkey-vs-flitkey/", "FlitKey vs AutoHotkey"), ("/textexpander-vs-flitkey/", "FlitKey vs TextExpander"), ("/atext-vs-flitkey/", "FlitKey vs aText")],
    },
    "migrations": {
        "tag": "MIGRATION GUIDES",
        "title": "Move text-expander libraries without losing the original",
        "description": "Reversible migration guidance for supported Espanso YAML, AutoHotkey, CSV, TSV, and JSON snippets.",
        "answer": "Treat migration as a controlled data conversion. Back up both tools, import one copied file, review the count and generated records, test a representative fixture, and retain the original until the important workflows pass. FlitKey imports supported snippet records; it does not reproduce every variable, script, form, macro, or application rule.",
        "sections": [
            ("inventory", "Inventory before converting", "<p>Count files, triggers, groups, dynamic variables, scripts, images, rich-text records, application filters, and shared-library dependencies. Mark each item as static text, convertible placeholder, automation, or unknown. Static text is the safest first batch. Unknown and automated entries deserve manual review before any import.</p><p>Also identify collisions. The same trigger may exist in multiple source files or already exist in FlitKey. Version 0.5.0 adds imported snippets and does not present a deduplication preview, so importing the same source twice can create duplicates.</p>"),
            ("backup", "Make rollback boring", "<p>Copy the entire source configuration rather than only the file you plan to import. Back up FlitKey's <code>config.json</code> as well. Store backups outside the live configuration directories and give them a date and tool version. A rollback should be a file restore, not a reconstruction from memory.</p><p>Pause one expander while testing the other. Two active processes listening for the same abbreviation can create duplicate output and make a correct import look broken.</p>"),
            ("formats", "Understand the supported shapes", "<p>Espanso YAML support is aimed at static <code>trigger</code> or <code>triggers</code> entries with text <code>replace</code> values and optional labels. Espanso variables, scripts, forms, regex, packages, and application conditions are not converted. AutoHotkey support recognizes supported hotstring and hotkey lines; it is not a general AutoHotkey interpreter.</p><p>CSV and TSV can use two columns for trigger and expansion or three for label, trigger, and expansion. JSON must contain recognizable snippet objects. Plain tabular export is useful for data movement, but it discards source-product behavior that has no matching column.</p>"),
            ("verify", "Verify content and behavior separately", "<p>First compare the imported label, trigger, and expansion with the source. Then test runtime behavior in a disposable editor. Include Unicode, newlines, punctuation, placeholders, and cursor placement. Finally test the real applications that matter. A correct record can still behave differently when an application handles synthetic input, clipboard paste, or elevated privileges differently.</p><p>On Wayland, do not use typed expansion as the acceptance test for FlitKey 0.5.0. Open Quick Insert, choose the rendered snippet, and paste it. The platform workflow is different even when the stored record is correct.</p>"),
            ("decision", "Know when not to migrate", "<p>Stay with Espanso if regex, forms, scripts, packages, and version-controlled YAML are central to the library. Keep AutoHotkey for window automation, remapping, and conditional Windows logic. Keep a commercial product when shared libraries, permissions, vendor support, mobile access, or rich content are requirements.</p><p>A partial migration is valid. FlitKey can own simple reusable text while another tool retains advanced automation, provided triggers do not conflict and the security implications of running both are acceptable.</p>"),
        ],
        "cards": [("/espanso-migration-guide", "Espanso migration walkthrough"), ("/autohotkey-vs-flitkey/#migration", "AutoHotkey migration section"), ("/docs#importers", "Importer file reference")],
    },
    "comparisons": {
        "tag": "PRODUCT COMPARISONS",
        "title": "Compare text expanders by the workflow they preserve",
        "description": "Decision-focused comparisons of FlitKey, Espanso, AutoHotkey, TextExpander, aText, and PhraseExpress.",
        "answer": "There is no universal winner. FlitKey fits individual Windows and Linux users who want visual, local, open-source text snippets. Espanso fits configuration-oriented automation. AutoHotkey fits broad Windows scripting. TextExpander fits synchronized team content. aText and PhraseExpress serve commercial desktop workflows with their own platform and feature strengths.",
        "sections": [
            ("method", "How these comparisons are evaluated", "<p>Each comparison starts with a short decision, names the user who should choose the competitor, and separates verified product behavior from planned testing. Feature tables use public source code for FlitKey and official vendor documentation for competitors. Pricing and platform statements require a dated check because they can change.</p><p>RAM, startup time, expansion latency, and application compatibility are not scored without a published method, named versions, machine details, a repeatable fixture, sample counts, and raw results. Removing a number is better than presenting an unverifiable advantage.</p>"),
            ("dimensions", "Five dimensions that change the decision", "<ol><li><strong>Platform:</strong> Windows, Linux X11, Linux Wayland, macOS, browser, or mobile.</li><li><strong>Workflow:</strong> plain text, rich content, forms, scripts, regex, or desktop automation.</li><li><strong>Management:</strong> individual files, visual editing, sync, shared groups, permissions, or administration.</li><li><strong>Data model:</strong> local storage, hosted sync, export format, and backup controls.</li><li><strong>Support:</strong> community project, commercial vendor, internal IT ownership, and update expectations.</li></ol>"),
            ("fit", "Where FlitKey is deliberately narrow", "<p>FlitKey provides a visual snippet manager, typed triggers and hotkeys on X11 and Windows, Quick Insert, local JSON storage, importers, expansion packs, and a small placeholder set. On Wayland it uses Quick Insert with clipboard paste. It has no macOS build, mobile client, cloud sync, shared-team administration, SSO, SCIM, or compliance certification.</p><p>Those omissions are acceptable for an individual who wants a local desktop utility. They disqualify FlitKey for many organizations. A comparison that hides those boundaries would generate downloads from the wrong audience and create avoidable support work.</p>"),
            ("reading", "Read the comparison that matches the switching trigger", "<p>Use the Espanso comparison when YAML friction, Wayland, or importability prompted the search. Use AutoHotkey when the question is whether text expansion still requires scripting. Use TextExpander when recurring cost, accounts, sync, or team features drive the decision. Use aText or PhraseExpress when evaluating commercial visual tools and Linux availability.</p><p>After choosing a likely fit, read the corresponding migration guide. A feature table can identify a tool; only a reversible test proves that the existing library and destination applications survive the move.</p>"),
            ("updates", "Treat comparisons as maintained documents", "<p>Every comparison names publication and update dates. A material release, pricing change, platform change, or importer change should trigger review. Screenshots, download links, schema, and visible claims must describe the same version.</p><p>If you find a stale claim, report it through the public issue tracker or contact page. Corrections should update the visible page, structured data, blog card, sitemap date, and machine-readable summaries together.</p>"),
        ],
        "cards": [("/espanso-vs-flitkey/", "FlitKey vs Espanso"), ("/autohotkey-vs-flitkey/", "FlitKey vs AutoHotkey"), ("/textexpander-vs-flitkey/", "FlitKey vs TextExpander"), ("/atext-vs-flitkey/", "FlitKey vs aText"), ("/phraseexpress-vs-flitkey/", "PhraseExpress vs FlitKey")],
    },
    "snippet-templates": {
        "tag": "SNIPPET PACK LIBRARY",
        "title": "Reusable text-expansion snippets you can inspect first",
        "description": "Free versioned JSON snippet packs for developers, support teams, sysadmins, AI prompts, productivity, and creative work.",
        "answer": "FlitKey 0.5.0 ships inspectable JSON packs for common workflows. Preview the raw file, check every trigger and command, load only the packs you need, and rename collisions before they enter daily use. Templates are starting points—not approved commands, security guidance, or finished customer communication.",
        "sections": [
            ("system", "Use a naming system before adding volume", "<p>A memorable trigger is short, distinct, and grouped with related triggers. Prefix support replies consistently, keep destructive commands visually obvious, and avoid ordinary words that can expand accidentally. A library with forty predictable names is more useful than hundreds of shortcuts nobody remembers.</p><p>Document the trigger, purpose, owner, platform, and last review date for important snippets. For shared files, include a pack identifier and version so users can tell which copy they loaded.</p>"),
            ("packs", "What the built-in packs cover", "<p>The developer pack includes examples for Git, Python, PowerShell, Markdown, Docker, and code scaffolds. The support pack covers greetings, issue intake, follow-up, and closing language. The sysadmin pack contains diagnostic and command examples. AI prompts provide reusable structures for explanation, refactoring, debugging, tests, and summaries.</p><p>Productivity and creative packs cover dates, symbols, common structures, design notes, and creator workflows. Counts and contents can change with releases, so the JSON file and in-app preview are more reliable than an old marketing total.</p>"),
            ("safety", "Review commands and prompts before use", "<p>Never run a shell, PowerShell, Docker, Kubernetes, or network command because it appeared in a template pack. Confirm the target, environment, privileges, quoting, and destructive effect. Replace example hosts, paths, identifiers, and credentials with safe values.</p><p>AI prompt templates can improve consistency, but they can also send confidential context to a third-party model if pasted without review. Remove private code, personal data, customer records, tokens, and internal instructions before submitting a prompt.</p>"),
            ("install", "Load a pack without overwriting your triggers", "<p>Open <strong>Expansion Packs</strong> in the FlitKey main window, select a pack, review the preview, and load it. The merge process keeps an existing snippet when the same trigger is already present. Platform filtering can exclude snippets that do not match the current operating system.</p><p>User-created packs live in the documented configuration pack directory and can override a built-in pack with the same pack identifier. Keep a backup and a version history before distributing a custom pack to other machines.</p>"),
            ("adapt", "Turn examples into a maintained library", "<p>Replace generic language with the tone, facts, links, and escalation paths your work actually uses. Add placeholders only when their output is predictable. Test multiline formatting and cursor placement in the destination application, not only in a plain editor.</p><p>Review packs quarterly. Remove obsolete commands, expired links, old product names, and replies that no longer match policy. A small maintained library compounds; an abandoned template dump becomes a source of mistakes.</p>"),
        ],
        "cards": [("https://raw.githubusercontent.com/swarajnandedkar/FlitKey/main/text_expander/packs/developer.json", "Developer JSON pack"), ("https://raw.githubusercontent.com/swarajnandedkar/FlitKey/main/text_expander/packs/support.json", "Support JSON pack"), ("https://raw.githubusercontent.com/swarajnandedkar/FlitKey/main/text_expander/packs/sysadmin.json", "Sysadmin JSON pack"), ("https://raw.githubusercontent.com/swarajnandedkar/FlitKey/main/text_expander/packs/ai_prompts.json", "AI prompts JSON pack")],
    },
    "privacy-security": {
        "tag": "PRIVACY & SECURITY",
        "title": "What a desktop text expander can observe and store",
        "description": "A practical threat model for keyboard hooks, local snippet storage, clipboard use, backups, updates, and compliance scope.",
        "answer": "A typed-trigger text expander must observe enough keyboard input to recognize its triggers on supported platforms. It also stores the text users ask it to reproduce. Local-only operation removes a hosted FlitKey service from the data path, but the endpoint, configuration file, clipboard, backups, destination applications, dependencies, and update process still matter.",
        "sections": [
            ("input", "Keyboard access is sensitive by definition", "<p>On Windows and X11, FlitKey monitors keyboard events to match enabled triggers and hotkeys. That capability is necessary for system-wide expansion and deserves the same scrutiny as other software with broad input access. On Wayland, FlitKey 0.5.0 does not implement global monitoring; it uses a user-opened picker and clipboard workflow.</p><p>Open source makes the implementation inspectable, but source availability is not proof that a downloaded binary matches the source or that every dependency is safe. Verify release provenance and follow endpoint policy.</p>"),
            ("storage", "Local storage changes who operates the server", "<p>FlitKey stores snippets and settings in a local JSON file under the user's configuration directory. It has no hosted account, central snippet database, or telemetry service. That reduces third-party data transfer and makes export and deletion understandable.</p><p>Local files remain exposed to the signed-in user, malware with equivalent access, administrators, disk images, search indexing, backup tools, and anyone who obtains an unencrypted device. Apply appropriate file permissions, full-disk encryption, account separation, and backup controls.</p>"),
            ("clipboard", "Clipboard workflows create a second copy", "<p>On Wayland, selecting a snippet places rendered text on the clipboard so the user can paste it. Clipboard managers may retain history. Remote desktop software and synchronized clipboards may copy the value elsewhere. Destination applications may log, sync, or submit the pasted text.</p><p>Disable clipboard history or synchronization where required, clear sensitive clipboard content, and do not use ordinary snippets as a password manager. Credentials, recovery codes, access tokens, private keys, and regulated records need purpose-built controls.</p>"),
            ("compliance", "Offline is not a compliance certification", "<p>FlitKey has not been certified for HIPAA, GDPR, CCPA, SOC 2, ISO 27001, or comparable standards and does not offer a Business Associate Agreement. Compliance depends on the organization, purpose, legal role, policies, access controls, retention, incident response, endpoint configuration, and downstream systems.</p><p>A security review can use FlitKey's public source, local storage paths, privacy notice, and dependency list as inputs. The result belongs to the organization performing the assessment.</p>"),
            ("controls", "A practical minimum control set", "<ul><li>Install only from a verified project source.</li><li>Keep the operating system and dependencies patched.</li><li>Use least-privilege accounts and full-disk encryption.</li><li>Exclude secrets and regulated records from ordinary snippets.</li><li>Review clipboard history, backups, and sync services.</li><li>Back up configuration securely and test deletion.</li><li>Reassess after major product or platform changes.</li></ul><p>Report suspected vulnerabilities privately through the documented security channel rather than placing exploit details or sensitive logs in a public issue.</p>"),
        ],
        "cards": [("/privacy", "Privacy notice"), ("/compliance", "Security and compliance scope"), ("/textexpander-vs-flitkey/", "Local versus synchronized workflows")],
    },
}


def header() -> str:
    return '''<header class="header"><nav class="container nav"><a class="nav-brand" href="/"><span class="brand-icon"></span><span class="brand-name">FlitKey</span></a><div class="nav-links" id="nav-links"><a class="nav-link" href="/">Home</a><a class="nav-link" href="/docs">Documentation</a><a class="nav-link active" href="/blogs">Blog &amp; Guides</a><a class="nav-link" href="/about">About</a></div><div class="nav-actions"><button id="theme-toggle" class="icon-btn" aria-label="Toggle color theme" title="Toggle color theme"><svg class="sun-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"></circle><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"></path></svg><svg class="moon-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg></button><a class="btn btn-primary nav-cta" href="/#download">Download Free</a><button id="mobile-menu-btn" class="mobile-menu-btn" aria-label="Toggle navigation menu"><span></span><span></span><span></span></button></div></nav></header>'''


def footer() -> str:
    return '''<footer class="footer"><div class="container footer-grid"><div class="footer-brand-col"><a class="nav-brand" href="/"><span class="brand-icon"></span><span class="brand-name">FlitKey</span></a><p class="footer-tagline">Local desktop text expansion for Windows and Linux.</p></div><div class="footer-col"><h4 class="footer-heading">Explore</h4><ul class="footer-links"><li><a href="/blogs">All articles</a></li><li><a href="/blogs/linux-text-expansion/">Linux guides</a></li><li><a href="/blogs/windows-text-expansion/">Windows guides</a></li><li><a href="/blogs/migrations/">Migrations</a></li></ul></div><div class="footer-col"><h4 class="footer-heading">Resources</h4><ul class="footer-links"><li><a href="/docs">Documentation</a></li><li><a href="/blogs/comparisons/">Comparisons</a></li><li><a href="/blogs/snippet-templates/">Snippet packs</a></li><li><a href="/blogs/privacy-security/">Privacy and security</a></li></ul></div></div><div class="container footer-bottom">&copy; 2026 FlitKey. Open source under the MIT License.</div></footer>'''


def build(slug: str, page: dict) -> str:
    canonical = f"https://flitkey.xyz/blogs/{slug}/"
    toc = "".join(f'<li><a href="#{section_id}">{html.escape(title)}</a></li>' for section_id, title, _ in page["sections"])
    sections = "".join(f'<section id="{section_id}" class="article-section"><h2>{html.escape(title)}</h2>{body}</section>' for section_id, title, body in page["sections"])
    cards = "".join(f'<a class="hub-card" href="{href}"><span class="blog-badge">Read next</span><h3>{html.escape(label)}</h3><p>Open the focused guide, comparison, or source file.</p></a>' for href, label in page["cards"])
    schema = json.dumps({"@context": "https://schema.org", "@graph": [{"@type": "CollectionPage", "name": page["title"], "description": page["description"], "url": canonical, "dateModified": "2026-08-03"}, {"@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "name": "Home", "item": "https://flitkey.xyz/"}, {"@type": "ListItem", "position": 2, "name": "Blog", "item": "https://flitkey.xyz/blogs"}, {"@type": "ListItem", "position": 3, "name": page["title"], "item": canonical}]}]}, separators=(",", ":"))
    return f'''<!doctype html><html lang="en" data-theme="light" data-accent="signal-red"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(page["title"])} | FlitKey</title><meta name="description" content="{html.escape(page["description"], quote=True)}"><meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large"><link rel="canonical" href="{canonical}"><link rel="stylesheet" href="../../styles.css"><meta property="og:type" content="website"><meta property="og:title" content="{html.escape(page["title"], quote=True)}"><meta property="og:description" content="{html.escape(page["description"], quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="https://flitkey.xyz/og-image.png"><script type="application/ld+json">{schema}</script></head><body class="docs-body">{header()}<main class="article-shell"><div class="article-meta">FlitKey editorial guide &bull; Updated August 3, 2026 &bull; Product behavior checked against FlitKey 0.5.0</div><header class="article-header"><span class="section-tag">{page["tag"]}</span><h1>{page["title"]}</h1><p class="article-deck">{page["description"]}</p></header><div class="direct-answer"><strong>Direct answer:</strong> {page["answer"]}</div><nav class="article-toc" aria-label="On this page"><h2>On this page</h2><ol>{toc}<li><a href="#next">Related guides</a></li></ol></nav>{sections}<section id="next" class="article-section"><h2>Related guides and source files</h2><div class="hub-grid">{cards}</div></section></main>{footer()}<script src="../../script.js"></script></body></html>'''


def main() -> None:
    for slug, page in PAGES.items():
        destination = ROOT / "blogs" / slug / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(build(slug, page), encoding="utf-8")
        print(destination)


if __name__ == "__main__":
    main()
